WITH value as (SELECT 
    history_id,
    car_type,
    daily_fee,
    DATEDIFF(END_DATE,START_DATE) + 1 as date_diff
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as H
JOIN CAR_RENTAL_COMPANY_CAR as C
ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '트럭')

SELECT 
*
FROM value
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
WHERE P.CAR_TYPE = '트럭'



  # CASE 
    #     WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN '90일 이상'
    #     WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 30 THEN '30일 이상'
    #     WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 7 THEN '7일 이상'
    # ELSE '7일 미만' END AS DURATION_TYPE

